name: Merge Master to develop
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  my-job:
    name: My Job
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: git checkout master
           git pull
           git checkout develop
           git merge master
           git push

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo merge master to develop completed.
